to follow coding standart

diff --git a/g3_amazon_download_old_api_study b/g3_amazon_download_old_api_study
--- a/g3_amazon_download_old_api_study
+++ b/g3_amazon_download_old_api_study
@@ -27,41 +27,41 @@
 #-----------------------------------------------------------------------------------------
 testing_download_old_api_study()
 {
-an_old_api_number=$1
-a_study_name=`prepare_testing_data ${an_old_api_number}`
+  an_old_api_number=$1
+  a_study_name=`prepare_testing_data ${an_old_api_number}`
 
-an_output_dir=${case_dir}.out
-an_abspath_files=`python -c "import os; print os.path.abspath(\"${case_dir}\")"`
+  an_output_dir=${case_dir}.out
+  an_abspath_files=`python -c "import os; print os.path.abspath(\"${case_dir}\")"`
 
-echo "-------------------- Testing amazon_download \"${an_old_api_number}\" api study ---------------------"
-amazon_download.py --study-name=${a_study_name} --output-dir=${an_output_dir} --enable-fresh --debug > log.amazon_download_old_api_study 2>&1
+  echo "-------------------- Testing amazon_download \"${an_old_api_number}\" api study ---------------------"
+  amazon_download.py --study-name=${a_study_name} --output-dir=${an_output_dir} --enable-fresh --debug > log.amazon_download_old_api_study 2>&1
 
-if [ $? -ne 0 ]; then
-   echo "An error have appeared during execution of amazon_dwonload.py" 
-   cat log.amazon_download_old_api_study
-   rm log.amazon_download_old_api_study
-   exit -1
-else
-   a_list_filenames=`create_list_filenames_in_casedir`
-   an_allright="True"
-   for a_file in ${a_list_filenames}
-   do
-      if [ ! -f ${an_output_dir}/${an_abspath_files}/${a_file} ]; then
-         an_allright="False"
-         a_bad_file=${a_file}
-         break
-      fi
-   done
-   if [ "${an_allright}" = "False" ]; then
-      echo " ERROR : There is no '${a_bad_file}' file , in output folder  '${an_output_dir}'. "
-      rm log.amazon_download_old_api_study
-      exit -1     
-   else
-      echo '----------------------------------- OK -----------------------------------------'
-      `remove_log_prepare_test_case`
-      echo ''
-   fi
-fi
+  if [ $? -ne 0 ]; then
+     echo "An error have appeared during execution of amazon_dwonload.py" 
+     cat log.amazon_download_old_api_study
+     rm log.amazon_download_old_api_study
+     exit -1
+  else
+     a_list_filenames=`create_list_filenames_in_casedir`
+     an_allright="True"
+     for a_file in ${a_list_filenames}
+     do
+        if [ ! -f ${an_output_dir}/${an_abspath_files}/${a_file} ]; then
+           an_allright="False"
+           a_bad_file=${a_file}
+           break
+        fi
+     done
+     if [ "${an_allright}" = "False" ]; then
+        echo " ERROR : There is no '${a_bad_file}' file , in output folder  '${an_output_dir}'. "
+        rm log.amazon_download_old_api_study
+        exit -1     
+     else
+        echo '----------------------------------- OK -----------------------------------------'
+        `remove_log_prepare_test_case`
+        echo ''
+     fi
+  fi
 }
 
 
diff --git a/g3_amazon_ls_old_api_files b/g3_amazon_ls_old_api_files
--- a/g3_amazon_ls_old_api_files
+++ b/g3_amazon_ls_old_api_files
@@ -25,40 +25,40 @@
 
 testing_ls_old_api_files()
 {
-an_old_api_number=$1
-a_study_name=`prepare_testing_data ${an_old_api_number}`
+  an_old_api_number=$1
+  a_study_name=`prepare_testing_data ${an_old_api_number}`
 
 
-echo "-------------------------- Testing amazon_ls \"${an_old_api_number}\" api files -----------------------------"
-amazon_ls.py ${a_study_name} --debug > log.amazon_ls_old_api_files 2>&1
+  echo "-------------------------- Testing amazon_ls \"${an_old_api_number}\" api files -----------------------------"
+  amazon_ls.py ${a_study_name} --debug > log.amazon_ls_old_api_files 2>&1
 
-if [ $? -ne 0 ] ; then
-   echo "An error have appeared during execution of amazon_ls.py" 
-   cat log.amazon_ls_old_api_files
-   rm log.amazon_ls_old_api_files
-   exit -1
-else
-   an_allright="True"
-   a_list_filenames=`create_list_filenames_in_casedir`
-   for a_filename in ${a_list_filenames}
-   do
-      count_entrances=`fgrep -c ${a_filename} log.amazon_ls_old_api_files`
-      if [ ${count_entrances} -eq 0 ]; then
-         an_allright="False"
-         a_not_exists_file=${a_filename}
-         break
-      fi
-   done 
-   if [ "${an_allright}" = "False" ]; then
-      echo " ERROR : There is no '${a_not_exists_file}' file in the s3 "
-      rm log.amazon_ls_old_api_files
-      exit -1
-   else
-      echo '----------------------------------- OK -----------------------------------------'
-      `remove_log_prepare_test_case`
-      echo ''
-   fi
-fi
+  if [ $? -ne 0 ] ; then
+     echo "An error have appeared during execution of amazon_ls.py" 
+     cat log.amazon_ls_old_api_files
+     rm log.amazon_ls_old_api_files
+     exit -1
+  else
+     an_allright="True"
+     a_list_filenames=`create_list_filenames_in_casedir`
+     for a_filename in ${a_list_filenames}
+     do
+        count_entrances=`fgrep -c ${a_filename} log.amazon_ls_old_api_files`
+        if [ ${count_entrances} -eq 0 ]; then
+           an_allright="False"
+           a_not_exists_file=${a_filename}
+           break
+        fi
+     done 
+     if [ "${an_allright}" = "False" ]; then
+        echo " ERROR : There is no '${a_not_exists_file}' file in the s3 "
+        rm log.amazon_ls_old_api_files
+        exit -1
+     else
+        echo '----------------------------------- OK -----------------------------------------'
+        `remove_log_prepare_test_case`
+        echo ''
+     fi
+  fi
 }
 
 
diff --git a/g3_amazon_ls_old_api_studies b/g3_amazon_ls_old_api_studies
--- a/g3_amazon_ls_old_api_studies
+++ b/g3_amazon_ls_old_api_studies
@@ -27,29 +27,29 @@
 #-----------------------------------------------------------------------------------------
 testing_ls_old_api_studies()
 {
-an_old_api_number=$1
-a_study_name=`prepare_testing_data ${an_old_api_number}`
+  an_old_api_number=$1
+  a_study_name=`prepare_testing_data ${an_old_api_number}`
 
-echo "------------------- Testing amazon_ls \"${an_old_api_number}\" api studies ----------------------"
-amazon_ls.py --debug > log.amazon_ls_old_api_study 2>&1
+  echo "------------------- Testing amazon_ls \"${an_old_api_number}\" api studies ----------------------"
+  amazon_ls.py --debug > log.amazon_ls_old_api_study 2>&1
 
-if [ $? -ne 0 ] ; then
-   echo "An error have appeared during execution of amazon_ls.py" 
-   cat log.amazon_ls_old_api_study
-   rm log.amazon_ls_old_api_study
-   exit -1
-else
-   count=`fgrep -c "${a_study_name}" log.amazon_ls_old_api_study`
-   if [ ${count} -gt 0 ] ; then 
-      echo '----------------------------------- OK -----------------------------------------'
-      `remove_log_prepare_test_case`
-      echo ''
-   else
-      echo " ERROR : There is no '${a_study_name}' study in the s3 "
-      rm log.amazon_ls_old_api_study
-      exit -1
-   fi   
-fi
+  if [ $? -ne 0 ] ; then
+     echo "An error have appeared during execution of amazon_ls.py" 
+     cat log.amazon_ls_old_api_study
+     rm log.amazon_ls_old_api_study
+     exit -1
+  else
+     count=`fgrep -c "${a_study_name}" log.amazon_ls_old_api_study`
+     if [ ${count} -gt 0 ] ; then 
+        echo '----------------------------------- OK -----------------------------------------'
+        `remove_log_prepare_test_case`
+        echo ''
+     else
+        echo " ERROR : There is no '${a_study_name}' study in the s3 "
+        rm log.amazon_ls_old_api_study
+        exit -1
+     fi   
+  fi
 }
 
 #-----------------------------------------------------------------------------------------
