advance test writing codding (unification with ec2 tests)

diff --git a/s3/g3_amazon_download_file b/s3/g3_amazon_download_file
--- a/s3/g3_amazon_download_file
+++ b/s3/g3_amazon_download_file
@@ -20,52 +20,36 @@
 
 
 #-----------------------------------------------------------------------------------------
-#source common function
-. s3.sh
+cd ${0%/*} || exit 1 # run from this directory
+source ./s3.sh
 
 
 #-----------------------------------------------------------------------------------------
-testing_download_file()
+test()
 {
+  echo "********************************************************************************"
+  echo $0
+
   a_script_name=`basename $0`
-  a_study_name=`prepare_testing_data`
   an_output_dir=${case_dir}.out
+  prepare_testing_data && a_study_name=`get_result`
   a_list_filenames=`create_list_filenames_in_casedir`
   a_downloading_file=`python -c "temp='${a_list_filenames}';_list=temp.split(' '); print _list[ 2 ]" `
 
-  echo "-------------------- Running \"${a_path_script}/${a_script_name}\" ----------------------"
-  a_testing_script="amazon_download.py --study-name=${a_study_name} --located-files=${a_downloading_file} --output-dir=${an_output_dir} --fresh --debug"
-  ${a_testing_script} > log.${a_script_name} 2>&1
-
-  if [ $? -ne 0 ]; then
-     echo ''
-     echo ''
-     echo "--------------------------------------------------------------------------------"
-     echo "An error have appeared during execution of"
-     echo "${a_testing_script}" 
-     echo "--------------------------------------------------------------------------------"
-     echo ''
-     echo ''
-     cat log.${a_script_name}
-     rm log.${a_script_name}
-     exit -1
-  else
-     if [ -f ${an_output_dir}/${a_downloading_file} ]; then
-        echo '----------------------------------- OK -----------------------------------------'
-     else
-        echo ''
-        echo ''
-        echo "--------------------------------------------------------------------------------"
-        echo " ERROR : There is no downloading file '${a_downloading_file}' , in '${an_output_dir}' folder "
-        echo "--------------------------------------------------------------------------------"
-        echo ''
-        echo ''
-        rm log.${a_script_name}
-        exit -1
-     fi
-  fi  
+  process_script "amazon_download.py --study-name=${a_study_name} --located-files=${a_downloading_file} --output-dir=${an_output_dir} --fresh --debug" 
+  if [ ! -f ${an_output_dir}/${a_downloading_file} ]; then
+      cat log.${a_script_name}
+      rm log.${a_script_name}
+      echo "--------------------------------------------------------------------------------"
+      echo " ERROR : There is no downloading file '${a_downloading_file}' , in '${an_output_dir}' folder "
+      echo "--------------------------------------------------------------------------------"
+      exit -1
+  fi
 }
 
 
-#-----------------------------------------------------------------------------------------------------------------------
-run_script testing_download_file
+#-----------------------------------------------------------------------------------------
+run_script test
+
+
+#-----------------------------------------------------------------------------------------
diff --git a/s3/g3_amazon_download_study b/s3/g3_amazon_download_study
--- a/s3/g3_amazon_download_study
+++ b/s3/g3_amazon_download_study
@@ -20,60 +20,45 @@
 
 
 #-----------------------------------------------------------------------------------------
-#source common function
-. s3.sh
+cd ${0%/*} || exit 1 # run from this directory
+source ./s3.sh
 
 
 #-----------------------------------------------------------------------------------------
-testing_download_study()
+test()
 {
+  echo "********************************************************************************"
+  echo $0
+
   a_script_name=`basename $0`
-  a_study_name=`prepare_testing_data`
   an_output_dir=${case_dir}.out
+  prepare_testing_data && a_study_name=`get_result`
 
-  echo "------------------- Running \"${a_path_script}/${a_script_name}\" ----------------------"
-  a_testing_script="amazon_download.py --study-name=${a_study_name} --output-dir=${an_output_dir} --fresh --debug"
-  ${a_testing_script} > log.${a_script_name} 2>&1
+  process_script "amazon_download.py --study-name=${a_study_name} --output-dir=${an_output_dir} --fresh --debug" 
 
-  if [ $? -ne 0 ]; then
-     echo ''
-     echo ''
-     echo "--------------------------------------------------------------------------------"
-     echo "An error have appeared during execution of" 
-     echo ${a_testing_script}
-     echo "--------------------------------------------------------------------------------"
-     echo ''
-     echo ''
-     cat log.${a_script_name}
-     rm log.${a_script_name}
-     exit -1
-  else
-     a_list_filenames=`create_list_filenames_in_casedir`
-     an_allright="True"
-     for a_file in ${a_list_filenames}
-     do
-        if [ ! -f ${an_output_dir}/${a_file} ]; then
-           an_allright="False"
-           a_bad_file=${a_file}
-           break
-        fi
-     done
-     if [ "${an_allright}" = "False" ]; then
-        echo ''
-        echo ''
-        echo "--------------------------------------------------------------------------------"
-        echo " ERROR : There is no '${a_bad_file}' file , in output folder  '${an_output_dir}'. "
-        echo "--------------------------------------------------------------------------------"
-        echo ''
-        echo ''
-        rm log.${a_script_name}
-        exit -1     
-     else
-        echo '----------------------------------- OK -----------------------------------------'
-     fi
+  a_list_filenames=`create_list_filenames_in_casedir`
+  an_allright="True"
+  for a_file in ${a_list_filenames} ; do
+      if [ ! -f ${an_output_dir}/${a_file} ]; then
+          an_allright="False"
+          a_bad_file=${a_file}
+          break
+      fi
+  done
+     
+  if [ "${an_allright}" = "False" ]; then
+      cat log.${a_script_name}
+      rm log.${a_script_name}
+      echo "--------------------------------------------------------------------------------"
+      echo " ERROR : There is no '${a_bad_file}' file , in output folder  '${an_output_dir}'. "
+      echo "--------------------------------------------------------------------------------"
+      exit -1     
   fi
 }
 
 
 #-----------------------------------------------------------------------------------------
-run_script testing_download_study
+run_script test
+
+
+#-----------------------------------------------------------------------------------------
diff --git a/s3/g3_amazon_ls_files b/s3/g3_amazon_ls_files
--- a/s3/g3_amazon_ls_files
+++ b/s3/g3_amazon_ls_files
@@ -20,61 +20,45 @@
 
 
 #-----------------------------------------------------------------------------------------
-#source common function
-. s3.sh
+cd ${0%/*} || exit 1 # run from this directory
+source ./s3.sh
 
 
 #-----------------------------------------------------------------------------------------
-testing_ls_files()
+test()
 {
-  a_script_name=`basename $0`
-  a_study_name=`prepare_testing_data`
+  echo "********************************************************************************"
+  echo $0
 
-  echo "---------------------- Running \"${a_path_script}/${a_script_name}\" -------------------------"
-  a_testing_script="amazon_ls.py ${a_study_name} --debug"
-  ${a_testing_script} > log.${a_script_name} 2>&1
- 
-  if [ $? -ne 0 ] ; then
-     echo ''
-     echo ''
-     echo "--------------------------------------------------------------------------------"
-     echo "An error have appeared during execution of " 
-     echo ${a_testing_script}
-     echo "--------------------------------------------------------------------------------"
-     echo ''
-     echo ''
-     cat log.${a_script_name}
-     rm log.${a_script_name}
-     exit -1
-  else
-     an_allright="True"
-     a_list_filenames=`create_list_filenames_in_casedir`
-     for a_filename in ${a_list_filenames}
-     do
-        count_entrances=`fgrep -c ${a_filename} log.${a_script_name}`
-        if [ ${count_entrances} -eq 0 ]; then
-           an_allright="False"
-           a_not_exists_file=${a_filename}
-           break
-        fi
-     done 
-     if [ "${an_allright}" = "False" ]; then
-        echo ''
-        echo ''
-        echo "--------------------------------------------------------------------------------"
-        echo " ERROR : There is no '${a_not_exists_file}' file in the s3 "
-        echo "--------------------------------------------------------------------------------"
-        echo ''
-        echo ''
-        cat log.${a_script_name}
-        rm log.${a_script_name}
-        exit -1
-     else
-        echo '----------------------------------- OK -----------------------------------------'
-     fi
-fi
+  a_script_name=`basename $0`
+  prepare_testing_data && a_study_name=`get_result`
+
+  process_script "amazon_ls.py ${a_study_name} --debug" 
+
+  an_allright="True"
+  a_list_filenames=`create_list_filenames_in_casedir`
+  for a_filename in ${a_list_filenames} ; do
+      count_entrances=`fgrep -c ${a_filename} log.${a_script_name}`
+      if [ ${count_entrances} -eq 0 ]; then
+          an_allright="False"
+          a_not_exists_file=${a_filename}
+          break
+      fi
+  done 
+
+  if [ "${an_allright}" = "False" ]; then
+      cat log.${a_script_name}
+      rm log.${a_script_name}
+      echo "--------------------------------------------------------------------------------"
+      echo " ERROR : There is no '${a_not_exists_file}' file in the s3 "
+      echo "--------------------------------------------------------------------------------"
+      exit -1
+  fi
 }
 
 
 #-----------------------------------------------------------------------------------------
-run_script testing_ls_files
+run_script test
+
+
+#-----------------------------------------------------------------------------------------
diff --git a/s3/g3_amazon_ls_pipe_rm_files b/s3/g3_amazon_ls_pipe_rm_files
--- a/s3/g3_amazon_ls_pipe_rm_files
+++ b/s3/g3_amazon_ls_pipe_rm_files
@@ -20,13 +20,12 @@
 
 
 #-----------------------------------------------------------------------------------------
-#source common function
-. s3.sh
-#a_study_name=`prepare_testing_data`
+cd ${0%/*} || exit 1 # run from this directory
+source ./s3.sh
 
 
 #-----------------------------------------------------------------------------------------
-testing_ls_pipe_rm_files()
+test()
 {
   a_script_name=`basename $0`
   an_output_dir=${case_dir}.out
@@ -35,75 +34,42 @@ testing_ls_pipe_rm_files()
   a_testing_files=`create_list_case_files ${a_testing_filenames}`
 
 
-  echo "------------------ Running \"${a_path_script}/${a_script_name}\" ---------------------"
-  a_testing_script="amazon_upload_start.py ${a_testing_files} --debug 2>log.prepare_data | amazon_upload_resume.py --debug 2>>log.prepare_data"
-  a_study_name=`bash -c "${a_testing_script}"`
-  if [ $? -ne 0 ]; then
-     echo ''
-     echo ''
-     echo "--------------------------------------------------------------------------------"
-     echo "An error have appeared during execution of "
-     echo ${a_testing_script}
-     echo "--------------------------------------------------------------------------------"
-     echo ''
-     echo ''
-     cat log.prepare_data
-     rm log.prepare_data
-     exit -1
-  fi
+  echo "********************************************************************************"
+  echo $0
 
-  a_testing_script="amazon_ls.py ${a_study_name} --debug 2>log.${a_script_name} | xargs amazon_rm.py --study-name=${a_study_name} --debug 2>>log.${a_script_name}"
-  bash -c "${a_testing_script}" > /dev/null
+  process_script "balloon-study-book --debug | amazon_upload_start.py ${a_testing_files} --debug | amazon_upload_resume.py --debug" 
+  a_study_name=`get_result`
 
-  if [ $? -ne 0 ]; then
-     echo ''
-     echo ''
-     echo "--------------------------------------------------------------------------------"
-     echo "An error have appeared during execution of"
-     echo ${a_testing_script}
-     echo "--------------------------------------------------------------------------------"
-     echo ''
-     echo ''
-     cat log.${a_script_name}
-     rm log.${a_script_name}
-     rm log.prepare_data
-     exit -1
+  process_script "amazon_ls.py ${a_study_name} --debug | xargs amazon_rm.py --study-name=${a_study_name} --debug"
+
+  amazon_ls.py ${a_study_name} --debug > log.check_ls_pipe_rm_files 2>&1
+  an_allright="True"
+  for a_filename in ${a_testing_filenames} ; do
+      count_entrances=`fgrep -c ${a_filename} log.check_ls_pipe_rm_files`
+      if [ ${count_entrances} -ne 0 ]; then
+          an_allright="False"
+          a_not_deleted_file=${a_filename}
+          break
+      fi
+  done
+  rm log.check_ls_pipe_rm_files
+
+  if [ "${an_allright}" = "False" ]; then
+      cat log.${a_script_name}
+      rm log.${a_script_name}
+      echo "--------------------------------------------------------------------------------"
+      echo " ERROR : The '${a_not_deleted_file}' file have not been removed from the s3 "
+      echo "--------------------------------------------------------------------------------"
+      exit -1
   else
-     amazon_ls.py ${a_study_name} --debug > log.check_ls_pipe_rm_files 2>&1
-     an_allright="True"
-     for a_filename in ${a_testing_filenames}
-     do
-        count_entrances=`fgrep -c ${a_filename} log.check_ls_pipe_rm_files`
-        if [ ${count_entrances} -ne 0 ]; then
-           an_allright="False"
-           a_not_deleted_file=${a_filename}
-           break
-        fi
-     done
-     if [ "${an_allright}" = "False" ]; then
-        echo ''
-        echo ''
-        echo "--------------------------------------------------------------------------------"
-        echo " ERROR : The '${a_not_deleted_file}' file have not been removed from the s3 "
-        echo "--------------------------------------------------------------------------------"
-        echo ''
-        echo ''
-        cat log.${a_script_name}
-        rm log.${a_script_name}
-        rm log.check_ls_pipe_rm_files
-        rm log.prepare_data
-        exit -1
-     else
-        echo '----------------------------------- OK -----------------------------------------'
-        rm log.check_ls_pipe_rm_files
-        rm log.prepare_data
-        `amazon_rm_study.py ${a_study_name} > tmp.log 2>&1`
-        rm tmp.log
-     fi
+      amazon_rm_study.py ${a_study_name} > tmp.log 2>&1
+      rm tmp.log
   fi
 }
 
 
 #-----------------------------------------------------------------------------------------
-run_script testing_ls_pipe_rm_files
+run_script test
 
+
+#-----------------------------------------------------------------------------------------
