to change running script to change error output now "ls pipe rm studies"  delete only studies which it create.

diff --git a/s3/g3_amazon_ls_pipe_rm_studies b/s3/g3_amazon_ls_pipe_rm_studies
--- a/s3/g3_amazon_ls_pipe_rm_studies
+++ b/s3/g3_amazon_ls_pipe_rm_studies
@@ -22,38 +22,43 @@
 #-----------------------------------------------------------------------------------------
 #source common function
 . common.sh
-#a_study_name=`prepare_testing_data`
 
 
 #-----------------------------------------------------------------------------------------
-#prepare testing data
-a_study_name1=`prepare_testing_data`
-`remove_log_prepare_test_case`
-a_study_name2=`prepare_testing_data`
+testing_ls_pipe_rm_studies()
+{
+  a_script_name=`basename $0`
+  a_study_name1=`prepare_testing_data`
+  `remove_log_prepare_test_case`
+  a_study_name2=`prepare_testing_data`
+  a_begin_study_name=`study_name_starts_with`
 
+  echo "----------------- Running \"${a_path_script}/${a_script_name}\" --------------------"
 
-#------------------------------------------------------------------------------------------
-a_begin_study_name=`study_name_starts_with`
+  amazon_ls.py --debug 2>log.${a_script_name} | grep -e ${a_study_name1} -e ${a_study_name2} | xargs amazon_rm_study.py --debug 2>>log.${a_script_name}
+  
+  if [ $? -ne 0 ]; then
+     echo "An error have appeared during execution of"
+     echo "amazon_ls.py --debug 2>log.${a_script_name} | grep -e ${a_study_name1} -e ${a_study_name2} | xargs amazon_rm_study.py --debug 2>>log.${a_script_name}" 
+     echo "--------------------------------------------------------------------------------"
+     cat log.${a_script_name}
+     rm log.${a_script_name}
+     exit -1
+  else
+     dummy=`amazon_ls.py --debug 2>log.check_ls_pipe_rm_studies`
+     count_entrances=`fgrep -c -e ${a_study_name1} -e ${a_study_name2} log.check_ls_pipe_rm_studies`
+     if [ ${count_entrances} -ne 0 ]; then
+        echo " ERROR : There is study named ${a_study_name1} or ${a_study_name2} ( may be both ) in the s3 "
+        cat log.${a_script_name}
+        rm log.${a_script_name}
+     else
+        echo '----------------------------------- OK -----------------------------------------'
+        rm log.check_ls_pipe_rm_studies
+        `remove_log_prepare_test_case`
+        `rm_from_studies ${a_study_name1} ${a_study_name2}`
+     fi
+  fi
+}
 
-echo '----------------------- Testing amazon_ls | rm studies -------------------------'
-
-amazon_ls.py --debug 2>log.ls_pipe_rm_studies | grep ${a_begin_study_name} | xargs amazon_rm_study.py --debug 2>>log.ls_pipe_rm_studies
-
-if [ $? -ne 0 ]; then
-   echo "An error have appeared during execution of 'amazon_ls.py | grep testing | xargs amazon_rm.py ' " 
-   rm log.ls_pipe_rm_studies
-   exit -1
-else
-   dummy=`amazon_ls.py --debug 2>log.check_ls_pipe_rm_studies`
-   count_entrances=`fgrep -c "${a_begin_study_name}" log.check_ls_pipe_rm_studies`
-   if [ ${count_entrances} -ne 0 ]; then
-      echo " ERROR : There are studies named 'testing-..' in the s3 "
-      cat log.ls_pipe_rm_studies
-      rm log.ls_pipe_rm_studies
-   else
-      echo '----------------------------------- OK -----------------------------------------'
-      rm log.check_ls_pipe_rm_studies
-      `remove_log_prepare_test_case`
-      `rm_studies`
-   fi
-fi
+#-----------------------------------------------------------------------------------------
+run_script testing_ls_pipe_rm_studies
