to change run script to change output error log

diff --git a/s3/g3_amazon_download_file b/s3/g3_amazon_download_file
--- a/s3/g3_amazon_download_file
+++ b/s3/g3_amazon_download_file
@@ -25,34 +25,35 @@
 
 
 #-----------------------------------------------------------------------------------------
-a_script_name=`basename $0`
-if [ -f log.${a_script_name} ]; then
-   echo "${a_script_name} already run: remove log file to run"
-   exit 0
-fi
+testing_download_file()
+{
+  a_study_name=`prepare_testing_data`
+  an_output_dir=${case_dir}.out
+  a_list_filenames=`create_list_filenames_in_casedir`
+  a_downloading_file=`python -c "temp='${a_list_filenames}';_list=temp.split(' '); print _list[ 2 ]" `
+
+  echo "----------------------- Running ${a_script_name} ------------------------"
+  a_testing_script="amazon_download.py --study-name=${a_study_name} --located-files=${a_downloading_file} --output-dir=${an_output_dir} --enable-fresh --debug"
+  ${a_testing_script} > log.${a_script_name} 2>&1
+
+  if [ $? -ne 0 ]; then
+     echo "An error have appeared during execution of ${a_command}" 
+     echo "--------------------------------------------------------------------------------"
+     cat log.${a_script_name}
+     rm log.${a_script_name}
+     exit -1
+  else
+     if [ -f ${an_output_dir}/${a_downloading_file} ]; then
+        echo '----------------------------------- OK -----------------------------------------'
+     else
+        echo " ERROR : There is no downloading file '${a_downloading_file}' , in '${an_output_dir}' folder "
+        echo "--------------------------------------------------------------------------------"
+        rm log.${a_script_name}
+        exit -1
+     fi
+  fi  
+}
 
 
-#-----------------------------------------------------------------------------------------
-a_study_name=`prepare_testing_data`
-an_output_dir=${case_dir}.out
-a_list_filenames=`create_list_filenames_in_casedir`
-a_downloading_file=`python -c "temp='${a_list_filenames}';_list=temp.split(' '); print _list[ 2 ]" `
-
-echo "----------------------- Running ${a_script_name} ------------------------"
-amazon_download.py --study-name=${a_study_name} --located-files=${a_downloading_file} --output-dir=${an_output_dir} --enable-fresh --debug > log.${a_script_name} 2>&1
-
-if [ $? -ne 0 ]; then
-   echo "An error have appeared during execution of amazon_dwonload.py" 
-   cat log.${a_script_name}
-   rm log.${a_script_name}
-   exit -1
-else
-   if [ -f ${an_output_dir}/${a_downloading_file} ]; then
-      echo '----------------------------------- OK -----------------------------------------'
-   else
-      echo " ERROR : There is no downloading file '${a_downloading_file}' , in '${an_output_dir}' folder "
-      rm log.${a_script_name}
-      exit -1
-   fi
-fi
-
+#-----------------------------------------------------------------------------------------------------------------------
+run_script testing_download_file
