to change error output and running script

diff --git a/s3/g3_amazon_rm_files b/s3/g3_amazon_rm_files
--- a/s3/g3_amazon_rm_files
+++ b/s3/g3_amazon_rm_files
@@ -22,43 +22,54 @@
 #-----------------------------------------------------------------------------------------
 #source common function
 . common.sh
-a_study_name=`prepare_testing_data`
 
 
 #-----------------------------------------------------------------------------------------
-echo '-------------------------- Testing amazon_rm files -----------------------------'
-a_list_filenames=`create_list_filenames_in_casedir`
-a_list_file_to_rm=`python -c "temp='${a_list_filenames}';_list=temp.split(' '); print _list[ 1 ],' ',_list[ 0 ]" `
+testing_rm_files()
+{
+  a_script_name=`basename $0`
+  a_study_name=`prepare_testing_data`
 
-amazon_rm.py --study-name=${a_study_name}  ${a_list_file_to_rm} --debug > log.amazon_rm_files 2>&1
-if [ $? -ne 0 ] ; then
-   echo "An error have appeared during execution of amazon_rm.py" 
-   cat log.amazon_rm_files
-   rm log.amazon_rm_files
-   exit -1
-else
-   amazon_ls.py ${a_study_name} --debug > log.list_files 2>&1
-   an_allright="True"
-   for a_file in ${a_list_file_to_rm}
-   do
-      count_entrances=`fgrep -c ${a_file}  log.list_files `
-      if [ ${count_entrances} -ne 0 ]; then
-         an_allright="False"
-         a_not_deleted_file=${a_filename}
-         break
-      fi
-   done
-   if [ "${an_allright}" = "False" ]; then
-      echo ' ERROR : The '${a_not_deleted_file}' file have not been removed from the s3 '
-      rm log.list_files
-      rm log.amazon_rm_files
-      exit -1
-   else
-      echo '----------------------------------- OK -----------------------------------------'
-      rm log.list_files 
-      `remove_log_prepare_test_case`
-   fi
-fi
+  echo "---------------------- Running \"${a_path_script}/${a_script_name}\" -------------------------"
+  a_list_filenames=`create_list_filenames_in_casedir`
+  a_list_file_to_rm=`python -c "temp='${a_list_filenames}';_list=temp.split(' '); print _list[ 1 ],' ',_list[ 0 ]" `
+
+  a_testing_script="amazon_rm.py --study-name=${a_study_name}  ${a_list_file_to_rm} --debug"
+  ${a_testing_script} > log.${a_script_name} 2>&1
+  if [ $? -ne 0 ] ; then
+     echo "An error have appeared during execution of" 
+     echo ${a_testing_script}
+     echo "--------------------------------------------------------------------------------"
+     cat log.${a_script_name}
+     rm log.${a_script_name}
+     exit -1
+  else
+     amazon_ls.py ${a_study_name} --debug > log.list_files 2>&1
+     an_allright="True"
+     for a_file in ${a_list_file_to_rm}
+     do
+        count_entrances=`fgrep -c ${a_file}  log.list_files `
+        if [ ${count_entrances} -ne 0 ]; then
+           an_allright="False"
+           a_not_deleted_file=${a_filename}
+           break
+        fi 
+     done
+     if [ "${an_allright}" = "False" ]; then
+        echo ' ERROR : The '${a_not_deleted_file}' file have not been removed from the s3 '
+        echo "--------------------------------------------------------------------------------"
+        rm log.list_files
+        cat log.${a_script_name}
+        rm log.${a_script_name}
+        exit -1
+     else
+        echo '----------------------------------- OK -----------------------------------------'
+        rm log.list_files 
+        `remove_log_prepare_test_case`
+     fi
+  fi
+}
 
 
 #-----------------------------------------------------------------------------------------
+run_script testing_rm_files
