to apply last changes( runnnig script and error message )

diff --git a/s3/g3_amazon_download_study b/s3/g3_amazon_download_study
--- a/s3/g3_amazon_download_study
+++ b/s3/g3_amazon_download_study
@@ -22,37 +22,46 @@
 #-----------------------------------------------------------------------------------------
 #source common function
 . common.sh
-a_study_name=`prepare_testing_data`
 
 
 #-----------------------------------------------------------------------------------------
-an_output_dir=${case_dir}.out
+testing_download_study()
+{
+  a_script_name=`basename $0`
+  a_study_name=`prepare_testing_data`
+  an_output_dir=${case_dir}.out
 
-echo '------------------------ Testing amazon_download study -------------------------'
-amazon_download.py --study-name=${a_study_name} --output-dir=${an_output_dir} --enable-fresh --debug > log.amazon_download_study 2>&1
+  echo "-------------------- Running \"${a_path_script}/${a_script_name}\" -----------------------"
+  a_testing_script="amazon_download.py --study-name=${a_study_name} --output-dir=${an_output_dir} --enable-fresh --debug"
+  ${a_testing_script} > log.${a_script_name} 2>&1
 
-if [ $? -ne 0 ]; then
-   echo "An error have appeared during execution of amazon_dwonload.py" 
-   cat log.amazon_download_study
-   rm log.amazon_download_study
-   exit -1
-else
-   a_list_filenames=`create_list_filenames_in_casedir`
-   an_allright="True"
-   for a_file in ${a_list_filenames}
-   do
-      if [ ! -f ${an_output_dir}/${a_file} ]; then
-         an_allright="False"
-         a_bad_file=${a_file}
-         break
-      fi
-   done
-   if [ "${an_allright}" = "False" ]; then
-      echo " ERROR : There is no '${a_bad_file}' file , in output folder  '${an_output_dir}'. "
-      rm log.amazon_download_study
-      exit -1     
-   else
-      echo '----------------------------------- OK -----------------------------------------'
-   fi
-fi
+  if [ $? -ne 0 ]; then
+     echo "An error have appeared during execution of" 
+     echo ${a_testing_script}
+     cat log.${a_script_name}
+     rm log.${a_script_name}
+     exit -1
+  else
+     a_list_filenames=`create_list_filenames_in_casedir`
+     an_allright="True"
+     for a_file in ${a_list_filenames}
+     do
+        if [ ! -f ${an_output_dir}/${a_file} ]; then
+           an_allright="False"
+           a_bad_file=${a_file}
+           break
+        fi
+     done
+     if [ "${an_allright}" = "False" ]; then
+        echo " ERROR : There is no '${a_bad_file}' file , in output folder  '${an_output_dir}'. "
+        rm log.${a_script_name}
+        exit -1     
+     else
+        echo '----------------------------------- OK -----------------------------------------'
+     fi
+  fi
+}
 
+
+#-----------------------------------------------------------------------------------------
+run_script testing_download_study
