to apply last changes( runnnig script and error message )

diff --git a/s3/g3_amazon_ls_files b/s3/g3_amazon_ls_files
--- a/s3/g3_amazon_ls_files
+++ b/s3/g3_amazon_ls_files
@@ -22,38 +22,46 @@
 #-----------------------------------------------------------------------------------------
 #source common function
 . common.sh
-a_study_name=`prepare_testing_data`
 
 
 #-----------------------------------------------------------------------------------------
-echo '-------------------------- Testing amazon_ls files -----------------------------'
-amazon_ls.py ${a_study_name} --debug > log.amazon_ls_files 2>&1
+testing_ls_files()
+{
+  a_script_name=`basename $0`
+  a_study_name=`prepare_testing_data`
 
-if [ $? -ne 0 ] ; then
-   echo "An error have appeared during execution of amazon_ls.py" 
-   cat log.amazon_ls_files
-   rm log.amazon_ls_files
-   exit -1
-else
-   an_allright="True"
-   a_list_filenames=`create_list_filenames_in_casedir`
-   for a_filename in ${a_list_filenames}
-   do
-      count_entrances=`fgrep -c ${a_filename} log.amazon_ls_files`
-      if [ ${count_entrances} -eq 0 ]; then
-         an_allright="False"
-         a_not_exists_file=${a_filename}
-         break
-      fi
-   done 
-   if [ "${an_allright}" = "False" ]; then
-      echo " ERROR : There is no '${a_not_exists_file}' file in the s3 "
-      rm log.amazon_ls_files
-      exit -1
-   else
-      echo '----------------------------------- OK -----------------------------------------'
-   fi
+  echo "-------------------- Running \"${a_path_script}/${a_script_name}\" -----------------------"
+  a_testing_script="amazon_ls.py ${a_study_name} --debug"
+  ${a_testing_script} > log.${a_script_name} 2>&1
+ 
+  if [ $? -ne 0 ] ; then
+     echo "An error have appeared during execution of " 
+     echo ${a_testing_script}
+     cat log.${a_script_name}
+     rm log.${a_script_name}
+     exit -1
+  else
+     an_allright="True"
+     a_list_filenames=`create_list_filenames_in_casedir`
+     for a_filename in ${a_list_filenames}
+     do
+        count_entrances=`fgrep -c ${a_filename} log.${a_script_name}`
+        if [ ${count_entrances} -eq 0 ]; then
+           an_allright="False"
+           a_not_exists_file=${a_filename}
+           break
+        fi
+     done 
+     if [ "${an_allright}" = "False" ]; then
+        echo " ERROR : There is no '${a_not_exists_file}' file in the s3 "
+        rm log.${a_script_name}
+        exit -1
+     else
+        echo '----------------------------------- OK -----------------------------------------'
+     fi
 fi
+}
 
 
 #-----------------------------------------------------------------------------------------
+run_script testing_ls_files
