to change errror output to change running script

diff --git a/s3/g3_amazon_upload_download_folder b/s3/g3_amazon_upload_download_folder
--- a/s3/g3_amazon_upload_download_folder
+++ b/s3/g3_amazon_upload_download_folder
@@ -22,48 +22,70 @@
 #-----------------------------------------------------------------------------------------
 #source common function
 . common.sh
-a_study_name=`create_study_name`
 
 
 #-----------------------------------------------------------------------------------------
-an_output_dir=${case_dir}.out
+testing_upload_dwonload_folder()
+{
+  a_script_name=`basename $0`
+  a_study_name=`create_study_name`
 
-echo '------------------------ Testing amazon_upload folder --------------------------'
-dummy=`amazon_upload_start.py --study-name=${a_study_name} ${case_dir} --debug 2>log.amazon_upload_folder | amazon_upload_resume.py --debug  2>>log.amazon_upload_folder`
-if [ $? -ne 0 ]; then
-   echo "An error have appeared during execution of amazon_upload_start.py | amazon_upload_resume.py" 
-   cat log.amazon_upload_folder
-   rm log.amazon_upload_folder
-   exit -1
-else
-   dummy=`amazon_ls.py ${a_study_name} --debug >log.check_upload_folder 2>&1`
-   count_entrances=`fgrep -c ${case_dir} log.check_upload_folder`
-   if [ ${count_entrances} -ne 0 ]; then
-      echo '----------------------------------- OK -----------------------------------------'
-      rm log.check_upload_folder
-   else
-      echo " ERROR : There is no uploading file '${case_dir}' , in the s3 "
-      rm log.amazon_download_file
-      exit -1
-   fi
-fi
+  an_output_dir=${case_dir}.out
 
-echo '----------------------- Testing amazon_download folder -------------------------'
-amazon_download.py --study-name=${a_study_name} --output-dir=${an_output_dir} --debug --enable-fresh > log.amazon_download_folder  2>&1
-if [ $? -ne 0 ]; then
-   echo "An error have appeared during execution of amazon_download.py" 
-   cat log.amazon_download_folder
-   rm log.amazon_download_folder
-   exit -1
-else
-   a_differences=`diff -r -q -i -x "*~" ${case_dir} ${an_output_dir}/${case_dir}`
-   if [ "x${a_differences}" == "x" ]; then
-      echo '----------------------------------- OK -----------------------------------------'   
-      dummy=`amazon_rm_study.py ${a_study_name} > log.tmp 2>&1`
-      rm log.tmp
-   else
-      echo "ERROR: There are differences between '${case_dir}' and '${an_output_dir}/${case_dir}': " 
-      echo ${a_differences}
-      exit -1
-   fi
-fi
+  echo "-------- Running \"${a_path_script}/${a_script_name}\" upload folder -----------"
+  
+  a_testing_script="amazon_upload_start.py --study-name=${a_study_name} ${case_dir} --debug 2>log.${a_script_name} | amazon_upload_resume.py --debug  2>>log.${a_script_name}"
+  dummy=`bash -c "${a_testing_script}"`
+  if [ $? -ne 0 ]; then
+     echo "An error have appeared during execution of " 
+     echo ${a_testing_script}
+     echo "--------------------------------------------------------------------------------"
+     cat log.${a_script_name}
+     rm log.${a_script_name}
+     exit -1
+  else
+     dummy=`amazon_ls.py ${a_study_name} --debug >log.check_upload_folder 2>&1`
+     count_entrances=`fgrep -c ${case_dir} log.check_upload_folder`
+     if [ ${count_entrances} -ne 0 ]; then
+        echo '----------------------------------- OK -----------------------------------------'
+        rm log.check_upload_folder
+        echo '----------------------------------------------------------------------------' > log.${a_script_name}
+     else
+        echo " ERROR : There is no uploading file '${case_dir}' , in the s3 "
+        rm log.${a_script_name}
+        exit -1
+     fi
+  fi
+
+  echo "------ Running \"${a_path_script}/${a_script_name}\" to download folder --------"
+  a_testing_script="amazon_download.py --study-name=${a_study_name} --output-dir=${an_output_dir} --debug --enable-fresh"
+  ${a_testing_script} >> log.${a_script_name}  2>&1
+  
+  if [ $? -ne 0 ]; then
+     echo "An error have appeared during execution of" 
+     echo ${a_testing_script}
+     echo "--------------------------------------------------------------------------------"
+     cat log.${a_script_name}
+     rm log.${a_script_name}
+     exit -1
+  else
+     a_differences=`diff -r -q -i -x "*~" ${case_dir} ${an_output_dir}/${case_dir}`
+     if [ "x${a_differences}" == "x" ]; then
+        echo '----------------------------------- OK -----------------------------------------'   
+        dummy=`amazon_rm_study.py ${a_study_name} > log.tmp 2>&1`
+        rm log.tmp
+     else
+        echo "ERROR: There are differences between '${case_dir}' and '${an_output_dir}/${case_dir}': " 
+        echo ${a_differences}
+        echo "--------------------------------------------------------------------------------"
+        cat log.${a_script_name}
+        rm log.${a_script_name}
+        exit -1
+     fi
+  fi
+}
+
+
+
+#-----------------------------------------------------------------------------------------
+run_script testing_upload_dwonload_folder
